// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Content for Brand documents
 */
interface BrandDocumentData {
  /**
   * Name field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Logo field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>
}

/**
 * Brand document from Prismic
 *
 * - **API ID**: `brand`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BrandDocumentData>, 'brand', Lang>

type CategoryDocumentDataSlicesSlice = HeroSmallSlice | ProductListSlice

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Slice Zone field in *Category*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoryDocumentDataSlicesSlice>
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    'category',
    Lang
  >

/**
 * Item in *Footer → Menu Links*
 */
export interface FooterDocumentDataMenuLinksItem {
  /**
   * Label field in *Footer → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Footer → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Footer → Partner logos*
 */
export interface FooterDocumentDataPartnerLogosItem {
  /**
   * Image field in *Footer → Partner logos*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.partner_logos[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Menu Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.menu_links[]
   * - **Tab**: Links
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_links: prismic.GroupField<Simplify<FooterDocumentDataMenuLinksItem>> /**
   * Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.visit_us_text
   * - **Tab**: Besök oss
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  visit_us_text: prismic.RichTextField /**
   * Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_us_text
   * - **Tab**: Kontakta oss
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_us_text: prismic.RichTextField /**
   * Partner logos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.partner_logos[]
   * - **Tab**: Partners
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partner_logos: prismic.GroupField<
    Simplify<FooterDocumentDataPartnerLogosItem>
  >
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
  >

/**
 * Item in *Header → Menu Links*
 */
export interface HeaderDocumentDataMenuLinksItem {
  /**
   * Label field in *Header → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Header → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Header → Mobile menu buttons*
 */
export interface HeaderDocumentDataMobileMenuButtonsItem {
  /**
   * Label field in *Header → Mobile menu buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.mobile_menu_buttons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Header → Mobile menu buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.mobile_menu_buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Header → Top bar*
 */
export interface HeaderDocumentDataTopBarItem {
  /**
   * Label field in *Header → Top bar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.top_bar[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Menu Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.menu_links[]
   * - **Tab**: Links
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_links: prismic.GroupField<Simplify<HeaderDocumentDataMenuLinksItem>>

  /**
   * Mobile menu buttons field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.mobile_menu_buttons[]
   * - **Tab**: Links
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  mobile_menu_buttons: prismic.GroupField<
    Simplify<HeaderDocumentDataMobileMenuButtonsItem>
  > /**
   * Top bar field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.top_bar[]
   * - **Tab**: Top bar
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  top_bar: prismic.GroupField<Simplify<HeaderDocumentDataTopBarItem>>
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    'header',
    Lang
  >

type HomepageDocumentDataSlicesSlice =
  | StatementSlice
  | DoubleBlockLargeSlice
  | DoubleBlockSmallSlice
  | HeroSlice
  | HeroSmallSlice
  | TextBlockSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaTitle
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaTitle: prismic.KeyTextField

  /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaDescription
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | DoubleBlockSmallSlice
  | DoubleBlockLargeSlice
  | StatementSlice
  | HeroSmallSlice
  | TextBlockSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaTitle
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaTitle: prismic.KeyTextField

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaDescription
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

type ProductDocumentDataSlicesSlice =
  | DoubleBlockSmallSlice
  | DoubleBlockLargeSlice
  | StatementSlice
  | TextBlockSlice

type ProductDocumentDataVariantsSlice = ProductVariantSlice

/**
 * Item in *Product → Images*
 */
export interface ProductDocumentDataImagesItem {
  /**
   * Image field in *Product → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Item in *Product → Documents*
 */
export interface ProductDocumentDataDocumentsItem {
  /**
   * Name field in *Product → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.documents[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * File field in *Product → Documents*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: product.documents[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Brand field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.brand
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand: prismic.ContentRelationshipField<'brand'>

  /**
   * Category field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<'category'>

  /**
   * Short description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variants[]
   * - **Tab**: Variants
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  variants: prismic.SliceZone<ProductDocumentDataVariantsSlice> /**
   * Primary image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.primary_image
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  primary_image: prismic.ImageField<never>

  /**
   * Images field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[]
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ProductDocumentDataImagesItem>> /**
   * Documents field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.documents[]
   * - **Tab**: Documents
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documents: prismic.GroupField<Simplify<ProductDocumentDataDocumentsItem>> /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.metaTitle
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaTitle: prismic.KeyTextField

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.metaDescription
   * - **Tab**: Seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProductDocumentData>, 'product', Lang>

/**
 * Content for Technical Product Data documents
 */
interface TechnicalProductDataDocumentData {
  /**
   * Category field in *Technical Product Data*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: technical_product_data.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | 'Värme'
    | 'Kyla'
    | 'Inomhusdel'
    | 'Utomhusdel'
    | 'El'
    | 'Köldmedium'
    | 'Rekommendation'
    | 'Modellbeteckning'
    | 'Trygghet'
  >

  /**
   * Title field in *Technical Product Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technical_product_data.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Unit field in *Technical Product Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technical_product_data.unit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  unit: prismic.KeyTextField
}

/**
 * Technical Product Data document from Prismic
 *
 * - **API ID**: `technical_product_data`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnicalProductDataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TechnicalProductDataDocumentData>,
    'technical_product_data',
    Lang
  >

export type AllDocumentTypes =
  | BrandDocument
  | CategoryDocument
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | PageDocument
  | ProductDocument
  | TechnicalProductDataDocument

/**
 * Primary content in *DoubleBlockLarge → Primary*
 */
export interface DoubleBlockLargeSliceDefaultSlicePrimary {
  /**
   * Progress Bar field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_block_large.primary.progressBar
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  progressBar: prismic.BooleanField

  /**
   * Background Color field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_large.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Image field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Stretch image field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_block_large.primary.stretch_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  stretch_image: prismic.BooleanField
}

/**
 * Primary content in *DoubleBlockLarge → Items*
 */
export interface DoubleBlockLargeSliceDefaultSliceItem {
  /**
   * Button Link field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for DoubleBlockLarge Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: DoubleBlockLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockLargeSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<DoubleBlockLargeSliceDefaultSlicePrimary>,
  Simplify<DoubleBlockLargeSliceDefaultSliceItem>
>

/**
 * Primary content in *DoubleBlockLarge → Primary*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithVideoPrimary {
  /**
   * Progress Bar field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_block_large.primary.progressBar
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  progressBar: prismic.BooleanField

  /**
   * Background Color field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_large.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Video field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField
}

/**
 * Primary content in *DoubleBlockLarge → Items*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithVideoItem {
  /**
   * Button Link field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Double Block Large With Video variation for DoubleBlockLarge Slice
 *
 * - **API ID**: `doubleBlockLargeWithVideo`
 * - **Description**: DoubleBlockLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockLargeSliceDoubleBlockLargeWithVideo =
  prismic.SharedSliceVariation<
    'doubleBlockLargeWithVideo',
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithVideoPrimary>,
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithVideoItem>
  >

/**
 * Primary content in *DoubleBlockLarge → Primary*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithFormPrimary {
  /**
   * Progress Bar field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_block_large.primary.progressBar
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  progressBar: prismic.BooleanField

  /**
   * Background Color field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_large.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Image field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Form title text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.formTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  formTitle: prismic.KeyTextField

  /**
   * Form Subtitle field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.formSubtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  formSubtitle: prismic.KeyTextField

  /**
   * Form Button text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.formButtonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  formButtonText: prismic.KeyTextField

  /**
   * Form Checkbox text field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Jag godkänner att bli kontaktad.
   * - **API ID Path**: double_block_large.primary.formCheckboxText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  formCheckboxText: prismic.RichTextField
}

/**
 * Primary content in *DoubleBlockLarge → Items*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithFormItem {
  /**
   * Button Link field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Double Block Large With Form variation for DoubleBlockLarge Slice
 *
 * - **API ID**: `doubleBlockLargeWithForm`
 * - **Description**: DoubleBlockLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockLargeSliceDoubleBlockLargeWithForm =
  prismic.SharedSliceVariation<
    'doubleBlockLargeWithForm',
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithFormPrimary>,
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithFormItem>
  >

/**
 * Primary content in *DoubleBlockLarge → Primary*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithTextsPrimary {
  /**
   * Progress Bar field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_block_large.primary.progressBar
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  progressBar: prismic.BooleanField

  /**
   * Background Color field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_large.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text Left field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.bodyTextLeft
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyTextLeft: prismic.RichTextField

  /**
   * Body Text Right field in *DoubleBlockLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.primary.bodyTextRight
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyTextRight: prismic.RichTextField
}

/**
 * Primary content in *DoubleBlockLarge → Items*
 */
export interface DoubleBlockLargeSliceDoubleBlockLargeWithTextsItem {
  /**
   * Button Link field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockLarge → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_large.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Double Block Large With Texts variation for DoubleBlockLarge Slice
 *
 * - **API ID**: `doubleBlockLargeWithTexts`
 * - **Description**: DoubleBlockLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockLargeSliceDoubleBlockLargeWithTexts =
  prismic.SharedSliceVariation<
    'doubleBlockLargeWithTexts',
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithTextsPrimary>,
    Simplify<DoubleBlockLargeSliceDoubleBlockLargeWithTextsItem>
  >

/**
 * Slice variation for *DoubleBlockLarge*
 */
type DoubleBlockLargeSliceVariation =
  | DoubleBlockLargeSliceDefaultSlice
  | DoubleBlockLargeSliceDoubleBlockLargeWithVideo
  | DoubleBlockLargeSliceDoubleBlockLargeWithForm
  | DoubleBlockLargeSliceDoubleBlockLargeWithTexts

/**
 * DoubleBlockLarge Shared Slice
 *
 * - **API ID**: `double_block_large`
 * - **Description**: DoubleBlockLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockLargeSlice = prismic.SharedSlice<
  'double_block_large',
  DoubleBlockLargeSliceVariation
>

/**
 * Primary content in *DoubleBlockSmall → Primary*
 */
export interface DoubleBlockSmallSliceDefaultSlicePrimary {
  /**
   * Background Color field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_small.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Image field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *DoubleBlockSmall → Items*
 */
export interface DoubleBlockSmallSliceDefaultSliceItem {
  /**
   * Button Link field in *DoubleBlockSmall → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockSmall → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for DoubleBlockSmall Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: DoubleBlockSmall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockSmallSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<DoubleBlockSmallSliceDefaultSlicePrimary>,
  Simplify<DoubleBlockSmallSliceDefaultSliceItem>
>

/**
 * Primary content in *DoubleBlockSmall → Primary*
 */
export interface DoubleBlockSmallSliceDoubleBlockSmallWithVideoPrimary {
  /**
   * Background Color field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: double_block_small.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'LightGrey', 'filled'>

  /**
   * Title Row 1 field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Body Text field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Video field in *DoubleBlockSmall → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField
}

/**
 * Primary content in *DoubleBlockSmall → Items*
 */
export interface DoubleBlockSmallSliceDoubleBlockSmallWithVideoItem {
  /**
   * Button Link field in *DoubleBlockSmall → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *DoubleBlockSmall → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_block_small.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Double Block Small With Video variation for DoubleBlockSmall Slice
 *
 * - **API ID**: `doubleBlockSmallWithVideo`
 * - **Description**: DoubleBlockSmall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockSmallSliceDoubleBlockSmallWithVideo =
  prismic.SharedSliceVariation<
    'doubleBlockSmallWithVideo',
    Simplify<DoubleBlockSmallSliceDoubleBlockSmallWithVideoPrimary>,
    Simplify<DoubleBlockSmallSliceDoubleBlockSmallWithVideoItem>
  >

/**
 * Slice variation for *DoubleBlockSmall*
 */
type DoubleBlockSmallSliceVariation =
  | DoubleBlockSmallSliceDefaultSlice
  | DoubleBlockSmallSliceDoubleBlockSmallWithVideo

/**
 * DoubleBlockSmall Shared Slice
 *
 * - **API ID**: `double_block_small`
 * - **Description**: DoubleBlockSmall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleBlockSmallSlice = prismic.SharedSlice<
  'double_block_small',
  DoubleBlockSmallSliceVariation
>

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultSlicePrimary {
  /**
   * Title Row 1 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow1: prismic.KeyTextField

  /**
   * Title Row 2 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleRow2: prismic.KeyTextField

  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Image Desktop field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageDesktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageDesktop: prismic.ImageField<never>

  /**
   * Image Mobile field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageMobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageMobile: prismic.ImageField<never>
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultSliceItem {
  /**
   * Button Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for Hero Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<HeroSliceDefaultSlicePrimary>,
  Simplify<HeroSliceDefaultSliceItem>
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefaultSlice

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *HeroSmall → Primary*
 */
export interface HeroSmallSliceDefaultSlicePrimary {
  /**
   * Background Color field in *HeroSmall → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: hero_small.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<'White' | 'Green', 'filled'>

  /**
   * Caption field in *HeroSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_small.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField

  /**
   * Title field in *HeroSmall → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_small.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Wide Title field in *HeroSmall → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_small.primary.wideTitle
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  wideTitle: prismic.BooleanField

  /**
   * Text field in *HeroSmall → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_small.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField

  /**
   * Button Link field in *HeroSmall → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_small.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *HeroSmall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_small.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for HeroSmall Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: HeroSmall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSmallSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<HeroSmallSliceDefaultSlicePrimary>,
  never
>

/**
 * Slice variation for *HeroSmall*
 */
type HeroSmallSliceVariation = HeroSmallSliceDefaultSlice

/**
 * HeroSmall Shared Slice
 *
 * - **API ID**: `hero_small`
 * - **Description**: HeroSmall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSmallSlice = prismic.SharedSlice<
  'hero_small',
  HeroSmallSliceVariation
>

/**
 * Primary content in *ProductList → Items*
 */
export interface ProductListSliceDefaultItem {
  /**
   * Product field in *ProductList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.items[].product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<'product'>
}

/**
 * Default variation for ProductList Slice
 *
 * - **API ID**: `default`
 * - **Description**: ProductList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ProductListSliceDefaultItem>
>

/**
 * Slice variation for *ProductList*
 */
type ProductListSliceVariation = ProductListSliceDefault

/**
 * ProductList Shared Slice
 *
 * - **API ID**: `product_list`
 * - **Description**: ProductList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductListSlice = prismic.SharedSlice<
  'product_list',
  ProductListSliceVariation
>

/**
 * Primary content in *ProductVariant → Primary*
 */
export interface ProductVariantSliceDefaultPrimary {
  /**
   * Name field in *ProductVariant → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_variant.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Energy field in *ProductVariant → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Energy rating
   * - **API ID Path**: product_variant.primary.energy
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  energy: prismic.SelectField<
    'A+++' | 'A++' | 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
  >

  /**
   * Size field in *ProductVariant → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 200
   * - **API ID Path**: product_variant.primary.size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  size: prismic.KeyTextField

  /**
   * Effect field in *ProductVariant → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 5.5
   * - **API ID Path**: product_variant.primary.effect
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  effect: prismic.KeyTextField

  /**
   * Cooling effect field in *ProductVariant → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 3.5
   * - **API ID Path**: product_variant.primary.effect_cold
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  effect_cold: prismic.KeyTextField

  /**
   * Price field in *ProductVariant → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_variant.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField

  /**
   * Price note field in *ProductVariant → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_variant.primary.price_note
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price_note: prismic.KeyTextField

  /**
   * 5 year warranty field in *ProductVariant → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_variant.primary.five_year_warranty
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  five_year_warranty: prismic.BooleanField
}

/**
 * Primary content in *ProductVariant → Items*
 */
export interface ProductVariantSliceDefaultItem {
  /**
   * Technical data field in *ProductVariant → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product_variant.items[].technical_data
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  technical_data: prismic.ContentRelationshipField<'technical_product_data'>

  /**
   * Value field in *ProductVariant → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_variant.items[].technical_data_value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  technical_data_value: prismic.KeyTextField
}

/**
 * Default variation for ProductVariant Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductVariantSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProductVariantSliceDefaultPrimary>,
  Simplify<ProductVariantSliceDefaultItem>
>

/**
 * Slice variation for *ProductVariant*
 */
type ProductVariantSliceVariation = ProductVariantSliceDefault

/**
 * ProductVariant Shared Slice
 *
 * - **API ID**: `product_variant`
 * - **Description**: ProductVariant
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductVariantSlice = prismic.SharedSlice<
  'product_variant',
  ProductVariantSliceVariation
>

/**
 * Primary content in *Statement → Primary*
 */
export interface StatementSliceDefaultSlicePrimary {
  /**
   * Title Row 1 field in *Statement → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleRow1: prismic.TitleField

  /**
   * Title Row 2 field in *Statement → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleRow2: prismic.TitleField

  /**
   * Body Text field in *Statement → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Graphic Elements field in *Statement → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: statement.primary.graphicElements
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  graphicElements: prismic.BooleanField
}

/**
 * Primary content in *Statement → Items*
 */
export interface StatementSliceDefaultSliceItem {
  /**
   * Button Link field in *Statement → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *Statement → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for Statement Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<StatementSliceDefaultSlicePrimary>,
  Simplify<StatementSliceDefaultSliceItem>
>

/**
 * Primary content in *Statement → Primary*
 */
export interface StatementSliceStatementWithBackgroundPrimary {
  /**
   * Title Row 1 field in *Statement → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.titleRow1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleRow1: prismic.TitleField

  /**
   * Title Row 2 field in *Statement → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.titleRow2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleRow2: prismic.TitleField

  /**
   * Body Text field in *Statement → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField

  /**
   * Graphic Elements field in *Statement → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: statement.primary.graphicElements
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  graphicElements: prismic.BooleanField

  /**
   * Background Image field in *Statement → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>

  /**
   * Dim Background field in *Statement → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 40
   * - **API ID Path**: statement.primary.dimBackground
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  dimBackground: prismic.SelectField<'40' | '60' | '80', 'filled'>
}

/**
 * Primary content in *Statement → Items*
 */
export interface StatementSliceStatementWithBackgroundItem {
  /**
   * Button Link field in *Statement → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *Statement → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Statement With Background variation for Statement Slice
 *
 * - **API ID**: `statementWithBackground`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSliceStatementWithBackground =
  prismic.SharedSliceVariation<
    'statementWithBackground',
    Simplify<StatementSliceStatementWithBackgroundPrimary>,
    Simplify<StatementSliceStatementWithBackgroundItem>
  >

/**
 * Slice variation for *Statement*
 */
type StatementSliceVariation =
  | StatementSliceDefaultSlice
  | StatementSliceStatementWithBackground

/**
 * Statement Shared Slice
 *
 * - **API ID**: `statement`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSlice = prismic.SharedSlice<
  'statement',
  StatementSliceVariation
>

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultSlicePrimary {
  /**
   * Content field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Primary content in *TextBlock → Items*
 */
export interface TextBlockSliceDefaultSliceItem {
  /**
   * Button Link field in *TextBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Button Label field in *TextBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField
}

/**
 * Default slice variation for TextBlock Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<TextBlockSliceDefaultSlicePrimary>,
  Simplify<TextBlockSliceDefaultSliceItem>
>

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefaultSlice

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  'text_block',
  TextBlockSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BrandDocument,
      BrandDocumentData,
      CategoryDocument,
      CategoryDocumentData,
      CategoryDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataMenuLinksItem,
      FooterDocumentDataPartnerLogosItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataMenuLinksItem,
      HeaderDocumentDataMobileMenuButtonsItem,
      HeaderDocumentDataTopBarItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      ProductDocumentDataVariantsSlice,
      ProductDocumentDataImagesItem,
      ProductDocumentDataDocumentsItem,
      TechnicalProductDataDocument,
      TechnicalProductDataDocumentData,
      AllDocumentTypes,
      DoubleBlockLargeSlice,
      DoubleBlockLargeSliceDefaultSlicePrimary,
      DoubleBlockLargeSliceDefaultSliceItem,
      DoubleBlockLargeSliceDoubleBlockLargeWithVideoPrimary,
      DoubleBlockLargeSliceDoubleBlockLargeWithVideoItem,
      DoubleBlockLargeSliceDoubleBlockLargeWithFormPrimary,
      DoubleBlockLargeSliceDoubleBlockLargeWithFormItem,
      DoubleBlockLargeSliceDoubleBlockLargeWithTextsPrimary,
      DoubleBlockLargeSliceDoubleBlockLargeWithTextsItem,
      DoubleBlockLargeSliceVariation,
      DoubleBlockLargeSliceDefaultSlice,
      DoubleBlockLargeSliceDoubleBlockLargeWithVideo,
      DoubleBlockLargeSliceDoubleBlockLargeWithForm,
      DoubleBlockLargeSliceDoubleBlockLargeWithTexts,
      DoubleBlockSmallSlice,
      DoubleBlockSmallSliceDefaultSlicePrimary,
      DoubleBlockSmallSliceDefaultSliceItem,
      DoubleBlockSmallSliceDoubleBlockSmallWithVideoPrimary,
      DoubleBlockSmallSliceDoubleBlockSmallWithVideoItem,
      DoubleBlockSmallSliceVariation,
      DoubleBlockSmallSliceDefaultSlice,
      DoubleBlockSmallSliceDoubleBlockSmallWithVideo,
      HeroSlice,
      HeroSliceDefaultSlicePrimary,
      HeroSliceDefaultSliceItem,
      HeroSliceVariation,
      HeroSliceDefaultSlice,
      HeroSmallSlice,
      HeroSmallSliceDefaultSlicePrimary,
      HeroSmallSliceVariation,
      HeroSmallSliceDefaultSlice,
      ProductListSlice,
      ProductListSliceDefaultItem,
      ProductListSliceVariation,
      ProductListSliceDefault,
      ProductVariantSlice,
      ProductVariantSliceDefaultPrimary,
      ProductVariantSliceDefaultItem,
      ProductVariantSliceVariation,
      ProductVariantSliceDefault,
      StatementSlice,
      StatementSliceDefaultSlicePrimary,
      StatementSliceDefaultSliceItem,
      StatementSliceStatementWithBackgroundPrimary,
      StatementSliceStatementWithBackgroundItem,
      StatementSliceVariation,
      StatementSliceDefaultSlice,
      StatementSliceStatementWithBackground,
      TextBlockSlice,
      TextBlockSliceDefaultSlicePrimary,
      TextBlockSliceDefaultSliceItem,
      TextBlockSliceVariation,
      TextBlockSliceDefaultSlice,
    }
  }
}
