// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  double_block_large: dynamic(() => import('./DoubleBlockLarge')),
  double_block_small: dynamic(() => import('./DoubleBlockSmall')),
  hero: dynamic(() => import('./Hero')),
  hero_small: dynamic(() => import('./HeroSmall')),
  product_list: dynamic(() => import('./ProductList')),
  product_variant: dynamic(() => import('./ProductVariant')),
  statement: dynamic(() => import('./Statement')),
  text_block: dynamic(() => import('./TextBlock')),
}
